name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ARTIFACTORY_SYS_USER: ${{ secrets.ARTIFACTORY_SYS_USER }}
      ARTIFACTORY_SYS_PASSWORD: ${{ secrets.ARTIFACTORY_SYS_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: SBT - Validate Code Formatting
          run: sbt clean scalafmtCheckAll
      - name: SBT - Publish
        run: sbt publish